##
# Update the DNF package cache and install packages as a root user
##
- name: Install required packages
  apt: name={{item}} state=latest
  become: yes
  with_items:
    - vim
    - fail2ban
    - python3
    - python3-dev
    - python3-venv
    - python3-setuptools
    - python-devel
    - gcc
    - git