##
# Update the DNF package cache and install packages as a root user
##
- name: Install required packages
  apt: name={{item}} state=latest update_cache=yes
  become: yes
  with_items:
    - acl
    - vim
    - python3
    - python3-venv
    - python3-apt
    - python3-setuptools
    - git
    - curl
    - zip
    - htop
    - vnstat
    - whois
    - mytop
    - rsync
    - supervisor