##
# Update the DNF package cache and install packages as a root user
##
- name: Install required packages
  apt: name={{item}} state=latest
  become: yes
  with_items:
    - acl
    - vim
    - python3
    - psycopg2
    - python3-setuptools
    - git