##
# Clone and pull the repo
##
- name: Set up git configuration
  apt: name=git state=latest
  become: yes

- name: Clone or pull the latest code
  become_flags: '-HE'
  become: yes
  become_user: encipher
  git: repo={{ code_repository_url }}
        accept_hostkey=yes
        dest={{ app_dir }}