##
# Set up and configure postgres
##
- name: Install and configure db
  apt: name={{item}} state=latest
  become: yes
  with_items:
    - postgresql
    - postgresql-contrib

#- name: Run initdb command
#  raw: initdb
#  become: yes

- name: Start and enable postgres
  service: name=postgresql enabled=yes state=started
  become: yes

- name: Create a virtualenv directory
  file: path={{ venv_dir }} state=directory

- name: Install dependencies
  pip:    requirements={{ app_dir }}/requirements.txt
          virtualenv={{ venv_dir }}
          virtualenv_python=python3

#- name: install psycopg2 python module
#  pip: name=psycopg2 virtualenv={{ venv_dir }}

- name: Create database
  postgresql_db: name={{ app_name }}
  become_user: postgres
  become: yes

- name: Configure a new postgresql user
  postgresql_user: db={{ app_name }}
                                name={{ db_user }}
                                password={{ db_password }}
                                priv=ALL
                                role_attr_flags=NOSUPERUSER
  become: yes
  become_user: postgres
  notify:
    - restart postgres